name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: System info
        run: |
          echo "Node version:"
          node --version
          echo "NPM version:"
          npm --version
          echo "Ubuntu version:"
          lsb_release -a
          echo "Current directory contents:"
          ls -la
          echo "Free disk space:"
          df -h

      - name: Install dependencies
        run: |
          npm ci
          echo "Node modules:"
          ls -la node_modules
          echo "Package lock contents:"
          cat package-lock.json

      - name: Build project
        run: |
          echo "Environment variables:"
          env
          echo "Package.json contents:"
          cat package.json
          echo "Starting build..."
          npm run build
        env:
          CI: true

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v4
        with:
          name: production-files
          path: ./dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: production-files
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist